### ISSUE TITLE
Feature Request: Allow Snapback to Run as Root

### ISSUE THREAD

**Issue by 3lpsy** [fkasler/snapback#1]
While it should discouraged, sometimes it may be useful to be able to run snapback as root. Currently, snapback fails to spawn chrome when run as the root user due to the sandbox requirement.

**Comment by fkasler** [comment]
The project includes a "No Sandbox" option to overcome Chrome's limitations running as root. Per the README:

'The "No Sandbox" setting is just to get around restrictions running the headless browser as root. It is really only useful for running the tool on Kali Linux or similar without needing to jump through a bunch of hoops.'

Please let me know if this does not solve your issue and we can look at more options. I will keep this thread open for now.

Thanks!

**Comment by 3lpsy** [comment]
I think it's fine to close it. I totally missed that in the Readme. Sorry about that :/

**Comment by fkasler** [comment]
No worries! I'm just glad it isn't broken :)
